extern const uint8_t AvantGarde_Book_12[];
extern const uint8_t AvantGarde_Book_24[];
extern const uint8_t AvantGarde_Book_36[];
extern const uint8_t Bookman_Demi_12[];
extern const uint8_t Bookman_Demi_24[];
extern const uint8_t Bookman_Demi_36[];
extern const uint8_t Courier_Bold_12[];
extern const uint8_t oledfont_Courier_Bold_24[];
extern const uint8_t Courier_Bold_36[];
extern const uint8_t Helvetica_12[];
extern const uint8_t Helvetica_24[];
extern const uint8_t Helvetica_36[];
extern const uint8_t Palatino_Roman_12[];
extern const uint8_t Palatino_Roman_24[];
extern const uint8_t Palatino_Roman_36[];
extern const uint8_t Utopia_12[];
extern const uint8_t Utopia_24[];
extern const uint8_t Utopia_36[];
const uint8_t *oledfont_AvantGarde_Book_12[];
const uint8_t *oledfont_Bookman_Demi_24[];
const uint8_t *oledfont_Helvetica_36[];
const uint8_t *oledfont_Palatino_Roman_24[];
const uint8_t *oledfont_Utopia_24[];
const uint8_t *oledfont_AvantGarde_Book_12[];
const uint8_t *oledfont_Bookman_Demi_24[];
const uint8_t *oledfont_Helvetica_36[];
const uint8_t *oledfont_Palatino_Roman_24[];
const uint8_t *oledfont_Utopia_24[];
const uint8_t *oledfont_AvantGarde_Book_12[];
const uint8_t *oledfont_Bookman_Demi_24[];
const uint8_t *oledfont_Helvetica_36[];
const uint8_t *oledfont_Palatino_Roman_24[];
const uint8_t *oledfont_Utopia_24[];
const uint8_t *oledfont_AvantGarde_Book_12[];
const uint8_t *oledfont_Bookman_Demi_24[];
const uint8_t *oledfont_Helvetica_36[];
const uint8_t *oledfont_Palatino_Roman_24[];
const uint8_t *oledfont_Utopia_24[];
